services:
  backend:
    build: ./backend
    ports:
      - 4000:4000

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - 3000:80

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
